Models/ErrorViewModel.cs
namespace OrdenesDeCompras.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/OrdenDeCompra.cs
using System.ComponentModel.DataAnnotations;
using OrdenesDeCompras.Validations;

namespace OrdenesDeCompras.Models
{
    public class OrdenDeCompra
    {
        [Key]
        [Required(ErrorMessage = "El campo Id es obligatorio.")]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo Número de Orden es obligatorio.")]
        [ValidationNumeroDeOrden]
        public required string NumeroDeOrden { get; set; }
        [Required(ErrorMessage = "El campo Fecha es obligatorio.")]
        [DataType(DataType.Date, ErrorMessage = "La fecha no tiene un formato válido.")]
        public DateTime Fecha { get; set; }
        [Required(ErrorMessage = "El campo Proveedor es obligatorio.")]
        public required string Proveedor { get; set; }
        [Required(ErrorMessage = "El campo Monto Total es obligatorio.")]
        [ValidationMontoTotal]
        public decimal MontoTotal { get; set; }
        [Required]
        public bool IsActive { get; set; } = true; 

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OrdenesDeCompras.Models;
using System.Diagnostics;

namespace OrdenesDeCompras.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OrdenDeCompraController.cs
using Microsoft.AspNetCore.Mvc;
using OrdenesDeCompras.Extensions;
using OrdenesDeCompras.Models;
using System.Collections.Generic;

namespace OrdenesDeCompras.Controllers
{
    public class OrdenDeCompraController : Controller
    {

        public IActionResult Index()
        {
            // Recuperar la lista de ordenes de compra desde la sesión
            var ordenes = ObtenerOrdenesDesdeSesion();

            if (ordenes == null || ordenes.Count == 0)
            {
                ViewData["Message"] = "No hay órdenes de compra guardadas.";
                return View();
            }

            return View(ordenes);
        }

        public IActionResult Crear()
        {

            return View(); 
        }


        [HttpPost]
        public IActionResult Crear(OrdenDeCompra orden)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                // Obtener la lista de órdenes almacenadas en la sesión
                var listaDeOrdenes = ObtenerOrdenesDesdeSesion();

                
                //if (listaDeOrdenes == null)
                //{
                //    listaDeOrdenes = new List<OrdenDeCompra>();
                //}
                

                orden.Id = listaDeOrdenes.Count > 0 ? listaDeOrdenes.Max(o => o.Id) + 1 : 1;
                orden.NumeroDeOrden = orden.NumeroDeOrden.Trim();
                orden.Proveedor = orden.Proveedor.Trim();
                listaDeOrdenes.Add(orden);

                // Guardar la lista actualizada en la sesión

                GuardarOrdenesEnSesion(listaDeOrdenes);

                return RedirectToAction("Index");
            }


            
        }

        public IActionResult Editar(int id)
        {
            var ordenes = ObtenerOrdenesDesdeSesion();
            var orden = ordenes.FirstOrDefault(o => o.Id == id);

            if (orden == null)
            {
                return NotFound();
            }

            return View(orden);
        }

        [HttpPost]
        public IActionResult Editar(OrdenDeCompra orden)
        {
            var listaDeOrdenes = ObtenerOrdenesDesdeSesion();
            if (!ModelState.IsValid)
            {
                // Verificar duplicidad (excepto para el mismo ID)
                if (listaDeOrdenes.Any(o => o.NumeroDeOrden.Trim() == orden.NumeroDeOrden.Trim() && o.Id != orden.Id))
                {
                    ModelState.AddModelError("NumeroDeOrden", "El número de orden ya existe. Por favor, ingrese un número único.");
                    return BadRequest(ModelState);
                }
            }


            var ordenExistente = listaDeOrdenes.FirstOrDefault(o => o.Id == orden.Id);

            if (ordenExistente != null)
            {
                ordenExistente.NumeroDeOrden = orden.NumeroDeOrden.Trim();
                ordenExistente.Fecha = orden.Fecha;
                ordenExistente.Proveedor = orden.Proveedor.Trim();
                ordenExistente.MontoTotal = orden.MontoTotal;
            }

            GuardarOrdenesEnSesion(listaDeOrdenes);
            return Json(new { success = true, message = "La orden se ha actualizado exitosamente." });
        }


        [HttpPost]
        public IActionResult ActivarDesactivarOrden(int id)
        {
            // Obtener la lista de órdenes desde la sesión
            var ordenes = ObtenerOrdenesDesdeSesion();

            // Buscar la orden por Id
            var orden = ordenes.FirstOrDefault(o => o.Id == id);

            if (orden == null)
            {
                return NotFound();
            }

            orden.IsActive = !orden.IsActive; 

            // Guardar la lista actualizada en la sesión
            GuardarOrdenesEnSesion(ordenes);

            return RedirectToAction("Index");
        }



        // Guardar la lista de órdenes en la sesión
        private void GuardarOrdenesEnSesion(List<OrdenDeCompra> ordenes)
        {
            HttpContext.Session.SetObject("OrdenesDeCompra", ordenes);
        }

        // Obtener la lista de órdenes desde la sesión
        private List<OrdenDeCompra> ObtenerOrdenesDesdeSesion()
        {
            return HttpContext.Session.GetObject<List<OrdenDeCompra>>("OrdenesDeCompra") ?? new List<OrdenDeCompra>();
        }

        [HttpPost]
        public IActionResult GenerarOrdenRandom(int cantidad)
        {
            var listaDeOrdenes = ObtenerOrdenesDesdeSesion();

			int nuevoId = listaDeOrdenes.Count > 0 ? listaDeOrdenes.Max(o => o.Id) + 1 : 1;

			List<OrdenDeCompra> ordenesGeneradas = new List<OrdenDeCompra>();

			for (int i = 0; i < cantidad; i++)
			{
				var orden = new OrdenDeCompra
				{
					Id = nuevoId++,
					NumeroDeOrden = $"ORD-{new Random().Next(1000, 9999)}",
					Fecha = GenerarFechaAleatoria(),
					Proveedor = GenerarProveedorAleatorio(),
					MontoTotal = Math.Round((decimal)(new Random().NextDouble() * 10000), 2),
					IsActive = new Random().Next(0, 2) == 1
				};

				ordenesGeneradas.Add(orden);
			}

			listaDeOrdenes.AddRange(ordenesGeneradas);

            GuardarOrdenesEnSesion(listaDeOrdenes);

			return Json(new { success = true, message = "Orden generada y guardada correctamente.", ordenesGeneradas });
		}


        // Generar una fecha aleatoria en los últimos 2 años
        private DateTime GenerarFechaAleatoria()
        {
            var fechaInicio = DateTime.Now.AddYears(-1);
            var fechaFin = DateTime.Now;

            int range = (fechaFin - fechaInicio).Days;
            return fechaInicio.AddDays(new Random().Next(range));
        }

        // Generar un nombre de proveedor aleatorio
        private string GenerarProveedorAleatorio()
        {
            var proveedores = new[] { "Proveedor A", "Proveedor B", "Proveedor C", "Proveedor D", "Proveedor E" };
            return proveedores[new Random().Next(proveedores.Length)];
        }



    }
}

Views/Home/Index.cshtml
@{
    
}


<div class="d-flex justify-content-center">
    <div class="card">
        <div class="card-details">
            <p class="text-title m-0">Examen Técnico - Programador Jr</p>
            <p class="text-body text-center">Ismael Antonio Plaza Pacheco</p>
        </div>
        <a class="card-button d-flex justify-content-center align-items-center" asp-area="" asp-controller="OrdenDeCompra" asp-action="Index">
            <i class="bi bi-play-fill me-1 fs-5"></i> Iniciar Prueba
        </a>

    </div>
</div>

Views/OrdenDeCompra/Crear.cshtml
@model OrdenDeCompra
@{
	ViewData["Title"] = "Crear";

}
@section Styles{
	<link href="~/css/OrdenDeCompra/Crear.css" rel="stylesheet" />
}
<div class="d-flex justify-content-between align-items-center mb-4">
	<h1>Crear orden de compra</h1>
	<a class="custom-button-delete d-flex align-items-center" asp-area="" asp-controller="OrdenDeCompra" asp-action="Index">
		<i class="bi bi-arrow-left me-1 fs-5"></i> Regresar
	</a>
</div>
<form asp-action="Crear" method="post" id="crearOrdenForm" class="needs-validation" novalidate>
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="row">
		<div class="col-md-8">
			<label class="sr-only" asp-for="NumeroDeOrden">Número de Orden</label>
			<div class="input-group mb-2">
				<div class="input-group-prepend">
					<div class="input-group-text"><i class="bi bi-file-earmark"></i></div>
				</div>
				<input asp-for="NumeroDeOrden" type="text" id="NumeroDeOrden" name="NumeroDeOrden" class="form-control" />
			</div>
			<span asp-validation-for="NumeroDeOrden" class="text-danger"></span>
		</div>
		<div class="col-md-4">
			<label class="sr-only" asp-for="Fecha">Fecha</label>
			<div class="input-group mb-2">
				<div class="input-group-prepend">
					<div class="input-group-text"><i class="bi bi-calendar"></i></div>
				</div>
				<input asp-for="Fecha" type="text" id="Fecha" name="Fecha" class="form-control" readonly/>
			</div>
			<span asp-validation-for="Fecha" class="text-danger"></span>

			<calendar-date id="FechaPicker" style="display: none; position: absolute; z-index: 9999;">
				<svg aria-label="Previous"
					 slot="previous"
					 xmlns="http://www.w3.org/2000/svg"
					 viewBox="0 0 24 24">
					<path d="M15.75 19.5 8.25 12l7.5-7.5"></path>
				</svg>
				<svg aria-label="Next"
					 slot="next"
					 xmlns="http://www.w3.org/2000/svg"
					 viewBox="0 0 24 24">
					<path d="m8.25 4.5 7.5 7.5-7.5 7.5"></path>
				</svg>
				
				<div class="grid">
					<calendar-month></calendar-month>
				</div>
            </calendar-date>
		</div>
	</div>
	<div class="form-group">
		<label class="sr-only" asp-for="Proveedor">Proveedor</label>
		<div class="input-group mb-2">
			<div class="input-group-prepend">
				<div class="input-group-text"><i class="bi bi-person-bounding-box"></i></div>
			</div>
			<input asp-for="Proveedor" type="text" id="Proveedor" name="Proveedor" class="form-control" />
		</div>
		<span asp-validation-for="Proveedor" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label class="sr-only" asp-for="MontoTotal">Monto Total</label>
		<div class="input-group mb-2">
			<div class="input-group-prepend">
				<div class="input-group-text"><i class="bi bi-currency-dollar"></i></div>
			</div>
			<input asp-for="MontoTotal" type="text" id="MontoTotal" name="MontoTotal" class="form-control" />
		</div>
		<span asp-validation-for="MontoTotal" class="text-danger"></span>
	</div>
	<button type="submit" class="custom-button-save d-flex align-items-center mt-3">
		<i class="bi bi-floppy me-1 fs-5"></i>Guardar
	</button>

</form>
<div id="loader" class="loader-container">
	<div class="loader">
		<div class="spinner"></div>
	</div>
</div>
@section Scripts{
	<script src="~/js/OrdenDeCompra/Crear.js"></script>
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Views/OrdenDeCompra/Editar.cshtml
@model OrdenDeCompra

@{
    ViewData["Title"] = "Editar";
}
@section Styles{
    <link href="~/css/OrdenDeCompra/Editar.css" rel="stylesheet" />
}

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1>Editar orden de compra</h1>
    <a class="custom-button-delete d-flex align-items-center" asp-area="" asp-controller="OrdenDeCompra" asp-action="Index">
        <i class="bi bi-arrow-left me-1 fs-5"></i> Regresar
    </a>
</div>
<form asp-action="Editar" method="post" id="editarOrdenForm">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-2">
            <label class="sr-only" asp-for="Id">Id de Orden</label>
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="bi bi-key"></i></div>
                </div>
                <input asp-for="Id" type="number" id="Id" name="Id" value="@Model.Id" class="form-control" readonly />
            </div>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div class="col-md-7">
            <label class="sr-only" asp-for="NumeroDeOrden">Número de Orden</label>
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="bi bi-file-earmark"></i></div>
                </div>
                <input asp-for="NumeroDeOrden" type="text" id="NumeroDeOrden" name="NumeroDeOrden" value="@Model.NumeroDeOrden" class="form-control" />
            </div>
            <span asp-validation-for="NumeroDeOrden" class="text-danger"></span>
        </div>
        <div class="col-md-3">
            <label class="sr-only" asp-for="Fecha">Fecha</label>
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="bi bi-calendar"></i></div>
                </div>
                <input type="hidden" id="FechaValue" value="@Model.Fecha" readonly />
                <input asp-for="Fecha" type="text" id="Fecha" name="Fecha" value="@Model.Fecha.ToString("dd/MM/yyyy")" class="form-control" readonly />
            </div>
            <span asp-validation-for="Fecha" class="text-danger"></span>

            <calendar-date id="FechaPicker" style="display: none; position: absolute; z-index: 9999;">
                <svg aria-label="Previous"
                     slot="previous"
                     xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 24 24">
                    <path d="M15.75 19.5 8.25 12l7.5-7.5"></path>
                </svg>
                <svg aria-label="Next"
                     slot="next"
                     xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 24 24">
                    <path d="m8.25 4.5 7.5 7.5-7.5 7.5"></path>
                </svg>

                <div class="grid">
                    <calendar-month></calendar-month>
                </div>
            </calendar-date>

        </div>
    </div>
    <div class="form-group">
        <label class="sr-only" asp-for="Proveedor">Proveedor</label>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="bi bi-person-bounding-box"></i></div>
            </div>
            <input asp-for="Proveedor" type="text" id="Proveedor" name="Proveedor" value="@Model.Proveedor" class="form-control" required />
        </div>
        <span asp-validation-for="Proveedor" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="sr-only" asp-for="MontoTotal">Monto Total</label>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="bi bi-currency-dollar"></i></div>
            </div>
            <input asp-for="MontoTotal" type="text" id="MontoTotal" name="MontoTotal" value="@Model.MontoTotal.ToString("0.00")" class="form-control" />
        </div>
        <span asp-validation-for="MontoTotal" class="text-danger"></span>
    </div>
    <button type="submit" class="custom-button-save d-flex align-items-center mt-3">
        <i class="bi bi-floppy me-1 fs-5"></i>Guardar
    </button>
</form>
<div id="loader" class="loader-container">
    <div class="loader">
        <div class="spinner"></div>
    </div>
</div>
@section Scripts{
    <script src="~/js/OrdenDeCompra/Editar.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/OrdenDeCompra/Index.cshtml
@model List<OrdenDeCompra>
@{
	ViewData["Title"] = "Listado";
}
@section Styles{
	<link href="~/css/OrdenDeCompra/Index.css" rel="stylesheet" />
}

<div class="container-fluid page-content">

	<div class="d-flex justify-content-between align-items-center mb-4">
		<h1>Listado de órdenes de compras</h1>

		<div class="d-flex gap-2">
			<button id="generarOrdenRandomBtn" class="custom-button-generate d-flex align-items-center me-3">
				<i class="bi bi-lightning me-1 fs-5"></i>Generar Orden
			</button>
			<a class="custom-button-add d-flex align-items-center" asp-area="" asp-controller="OrdenDeCompra" asp-action="Crear"><i class="bi bi-plus-circle me-1 fs-5"></i>Nueva orden de compra</a>
		</div>
	</div>

	<div class="container-fluid d-flex d-column mt-10 table-info">

		<div class="table-responsive w-100 mx-10">
			<div class="search-container mb-3">
				<i class="bi bi-search"></i>
				<input type="text" id="customSearch" class="" placeholder="Buscar" />
			</div>
			@if (Model != null && Model.Any())
			{
				<table class="display" id="OrdenesDeCompras">
					<thead>
						<tr>
							<th>Id</th>
							<th>Número de Orden</th>
							<th>Fecha</th>
							<th>Proveedor</th>
							<th>Monto Total</th>
							<th class="text-center">Estatus</th>
							<th class="text-center">Acciones</th>
						</tr>
					</thead>

					<tbody>
						@foreach (var orden in Model)
						{
							<tr>
								<td>@orden.Id</td>
								<td>@orden.NumeroDeOrden</td>
								<td>@orden.Fecha.ToString("dd/MM/yyyy")</td>
								<td>@orden.Proveedor</td>
								<td>@String.Format(new System.Globalization.CultureInfo("en-US"), "{0:C}", orden.MontoTotal)</td>
								<td class="text-center">
									<div class="d-flex justify-content-center align-items-center">
										<button class="btn @(orden.IsActive ? "btn-activo" : "btn-inactivo") pe-none">
											@(orden.IsActive ? "Activa" : "Inactiva")
										</button>
									</div>
								</td>
								<td class="text-center">
									<div class="dropdown">
										<button class="btn custom-button-option" type="button" id="dropdownMenuButton_@orden.Id" data-bs-toggle="dropdown" aria-expanded="false">
											<i class="bi bi-gear fs-5"></i>
										</button>
										<ul class="dropdown-menu p-0" aria-labelledby="dropdownMenuButton_@orden.Id">
											<li>
												<a class="dropdown-item d-flex align-items-center" asp-controller="OrdenDeCompra" asp-action="Editar" asp-route-id="@orden.Id">
													<i class="bi bi-pencil-square me-2"></i>Editar
												</a>
											</li>
											<li>
												<form method="post" asp-action="ActivarDesactivarOrden" asp-route-id="@orden.Id" class="activarDesactivarForm">
													<button type="button" class="dropdown-item activarDesactivarBtn d-flex align-items-center"
															data-id="@orden.Id"
															data-status="@(orden.IsActive ? "desactivar" : "activar")">
														<i class="bi bi-@(orden.IsActive ? "x-circle" : "check-circle")  pencil-square me-2"></i>@(orden.IsActive ? "Desactivar" : "Activar")
													</button>
												</form>
											</li>
										</ul>
									</div>



								</td>
							</tr>
						}

					</tbody>
				</table>
			}
			else
			{
				<table class="display" id="OrdenesDeCompras">
					<thead>
						<tr>
							<th>Id</th>
							<th>Número de Orden</th>
							<th>Fecha</th>
							<th>Proveedor</th>
							<th>Monto Total</th>
							<th class="text-center">Estatus</th>
							<th class="text-center">Acciones</th>
						</tr>
					</thead>

					<tbody>
					</tbody>
				</table>
			}


		</div>

	</div>
</div>
<div id="loader" class="loader-container">
	<div class="loader">
		<div class="spinner"></div>
	</div>
</div>
@section Scripts{
	<script src="~/js/OrdenDeCompra/Index.js"></script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrdenesDeCompras</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrdenesDeCompras.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/inputmask@5.0.9/dist/colormask.min.css">
    <link rel="stylesheet" href="https://unpkg.com/cally@latest/dist/cally.css" />


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    @RenderSection("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OrdenesDeCompras</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - OrdenesDeCompras - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/inputmask@5.0.9/dist/jquery.inputmask.min.js"></script>

    <script type="module" src="https://unpkg.com/cally"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>